[manifest]
version = "1.0.0"
priority = 0


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "            if add and not G.GAME.banned_keys[v.key] then"
position = "before"
payload = '''
        if _type == "kity" then
            --local legtext = _legendary and "true" or "false"
            --mintySay("key == "..v.key.."; _legendary == "..legtext.."; rarity == "..v.rarity, "TRACE")
            if _legendary and v.rarity ~= 4 then
                add = nil
            end
            --if add then mintySay("Joker Boy Allowed", "TRACE") else mintySay("No Joker Allowed", "TRACE") end
        end
'''
match_indent = true





