[manifest]
version = "1.0.0"
priority = 1

# Remove non-legendary kitys from pool when using The Wand
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "            if add and not G.GAME.banned_keys[v.key] then"
position = "before"
payload = '''
        if _type == "kity" then
            --local legtext = _legendary and "true" or "false"
            --mintySay("key == "..v.key.."; _legendary == "..legtext.."; rarity == "..v.rarity, "TRACE")
            if _legendary and v.rarity ~= 4 then
                add = nil
            end
            --if add then mintySay("Joker Boy Allowed", "TRACE") else mintySay("No Joker Allowed", "TRACE") end
        end
'''
match_indent = true

# Add Paperback cross-mod content to Paper Deck boost pool
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if (G.GAME.selected_back_key or {}).key == 'b_paperback_paper' and v.key:find('j_paperback_') then"
position = "at"
payload = "if (G.GAME.selected_back_key or {}).key == 'b_paperback_paper' and (v.key:find('j_paperback_') or (v.pools and v.pools.Paperback)) then"
match_indent = true

# Add Ortalab crossover content to Ortalab stakes
[[patches]]
[patches.pattern]
target = '=[SMODS ortalab "objects/stakes.lua"]'
position = "after"
pattern = "if not v.mod or v.mod.id ~= 'ortalab' then add = false end"
payload =  "if (v.pools and v.pools.Ortalab) then add = true end"
match_indent = true