[manifest]
version = "1.0.0"
priority = 0

# Cement Seal: Always scores. (this doesn't seem to be elegantly hookable rip in pepperonis)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
position = "at"
pattern = "            if G.play.cards[i].ability.effect == 'Stone Card' then"
payload = "            if G.play.cards[i].ability.effect == 'Stone Card' or G.play.cards[i].seal == 'minty_cement' then"
match_indent = true

# Treat-o-vision resets on game start
[[patches]]
[patches.pattern]
target = "game.lua"
position = "after"
pattern = "        reset_castle_card()"
payload = "        reset_treat_card()"
match_indent = true