[manifest]
version = "1.0.0"
priority = 1

# Remove non-legendary kitys from pool when using The Bitz and The Wand
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "            if add and not G.GAME.banned_keys[v.key] then"
position = "before"
payload = '''
        if _type == "kity" then
            --local legtext = _legendary and "true" or "false"
            --MINTY.say("key == "..v.key.."; rarity == "..v.rarity, "TRACE")
            if _legendary and v.rarity ~= 4 then
                add = nil
            end
            if (not _legendary) and v.rarity == 4 then
                add = nil
            end
            --if add then MINTY.say("Joker Boy Allowed", "TRACE") else MINTY.say("No Joker Allowed", "TRACE") end
        end
'''
match_indent = true

# Add Paperback cross-mod content to Paper Deck boost pool
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if (G.GAME.selected_back_key or {}).key == 'b_paperback_paper' and v.key:find('j_paperback_') then"
position = "at"
payload = "if (G.GAME.selected_back_key or {}).key == 'b_paperback_paper' and (v.key:find('j_paperback_') or (v.pools and v.pools.Paperback)) then"
match_indent = true

# Add Ortalab crossover content to Ortalab stakes
[[patches]]
[patches.pattern]
target = '=[SMODS ortalab "objects/stakes.lua"]'
position = "after"
pattern = "if not v.mod or v.mod.id ~= 'ortalab' then add = false end"
payload =  "if (v.pools and v.pools.Ortalab) then add = true end"
match_indent = true

# Stop hyperfix count when a Joker is bought
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = "after"
pattern = "elseif c1.ability.set == 'Joker' then"
payload =  '''
if G.GAME.minty_hyperfix then G.GAME.minty_hyperfix.active = false
else G.GAME.minty_hyperfix = { active = false, value = 0 }
end
'''
match_indent = true

# Increment hyperfix count when a blind is skipped
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = "after"
pattern = "G.GAME.skips = (G.GAME.skips or 0) + 1"
payload =  '''
    if G.GAME.minty_hyperfix.active then
        G.GAME.minty_hyperfix.value = (G.GAME.minty_hyperfix.value or 0) + 1
    end
'''
match_indent = true

# Count lucky triggers (disabled atm cause our one thing is no longer counting globally)
[[patches]]
[patches.pattern]
target = "card.lua"
position = "after"
pattern = "self.lucky_trigger = true"
payload =  "--MINTY.luckyCount()"
match_indent = true