SMODS.Gradient{
    key = "garbled_handbuff",
    colours = {
        G.C.RED,
        G.C.GOLD,
        G.C.GREEN,
        G.C.WHITE,
        G.C.BLUE,
        G.C.GREEN,
        HEX("CA7CA7"),
        G.C.GOLD,
        HEX("CA7CA7"),
        G.C.BLUE,
        G.C.PURPLE,
        G.C.WHITE,
        G.C.GREEN,
        HEX("CA7CA7"),
        G.C.GOLD,
        G.C.BLUE,
        G.C.GREEN,
        HEX("CA7CA7"),
        G.C.PURPLE,
        G.C.GREEN,
        G.C.WHITE,
        HEX("CA7CA7"),
    },
    cycle = 2
}