[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.GAME.blind and G.boss_throw_hand and self.STATE == self.STATES.SELECTING_HAND then"
position = 'after'
match_indent = true
payload = '''
if G.GAME.minty_blackjack_count ~= G.GAME.minty_blackjack and G.boss_throw_hand then
    if G.GAME.minty_last_blackjack_count ~= G.GAME.minty_blackjack_count then
        if self.boss_warning_text then 
            self.boss_warning_text:remove()
            self.boss_warning_text = nil
        end
        G.GAME.minty_last_blackjack_count = G.GAME.minty_blackjack_count
    end
end
'''