[manifest]
version = "1.0.0"
priority = -1

# Calculate tags when blind is almost defeated
[[patches]]
[patches.pattern]
target = "game.lua"
position = "before"
pattern = "if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then"
payload = '''
if to_big(G.GAME.chips) >= to_big(G.GAME.blind.chips) then
    --MINTY.say("Checking tags before boss defeat...")
    for i = 1, #G.GAME.tags do
        G.GAME.tags[i]:apply_to_run({type = 'blind_defeated_check'})
    end
end
'''
match_indent = true

# Open *A* pack at beginning of shop
[[patches]]
[patches.pattern]
target = "game.lua"
position = "after"
pattern = '''
for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'shop_start'})
end
'''
payload = '''
for i = 1, #G.GAME.tags do
    if G.GAME.tags[i]:apply_to_run({type = 'shop_start_once'}) then break end
end
'''
match_indent = true